=== MrLogEN/4iz238-sp/schemas/diet_tracker.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:vse:4iz238:chav07:sp:diet_tracker"
           xmlns="urn:vse:4iz238:chav07:sp:diet_tracker"
           elementFormDefault="qualified">

    <!-- Schema for diet_tracker XML -->
    <!-- Fill in the schema definitions here -->
    <xs:element name="diet_tracker" type="diet_tracker_type"/>
       
     <!-- Diet tracker type -->
    <xs:complexType name="diet_tracker_type">
        
        <xs:sequence>
            <xs:element name="user" type="user_type"/>
        </xs:sequence>
        <xs:attribute name="version" use="required" type="version_type"/>
        
    </xs:complexType>
    
    <!-- Version type -->
    <xs:simpleType name="version_type">
        <xs:annotation>
            <xs:documentation>
                The version must be in simplified SemVer major.minor format (i.e. 1.1, 3.2, etc.).
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+\.\d+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- user type -->
    <xs:complexType name="user_type">
        <xs:sequence>
            <xs:element name="name" type="user_name_type"/>
            <xs:element name="email" type="user_email_type"/>
            <xs:element name="date_of_birth" type="xs:date"/>
            <xs:element name="sex" type="sex_type"/>
            <xs:element name="current_state" type="current_state_type"/>
            <xs:element name="long_term_goals" type="long_term_goals_type"/>
            <xs:element name="daily_logs" type="daily_logs_type"/>
        </xs:sequence> 
        <!-- user ID attribute -->
        <xs:attribute name="id" type="xs:nonNegativeInteger" use="required"/>
    </xs:complexType>
    
    <!-- user name type -->
    <xs:simpleType name="user_name_type">
        <xs:annotation>
            <xs:documentation>
                The name of the user. Must contain at least one non-whitespace character.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value=".*\S.*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- user email type -->
    <xs:simpleType name="user_email_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- sex type -->
    <xs:simpleType name="sex_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="male"/>
            <xs:enumeration value="female"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- current state type -->
    <xs:complexType name="current_state_type">
        <xs:sequence>
            <xs:element name="height" type="height_type"/>
            <xs:element name="weight" type="weight_type"/>
        </xs:sequence>
    </xs:complexType>
    
    
    <!-- Height type -->
    <xs:simpleType name="height_type">
        <xs:annotation>
            <xs:documentation>
                Height in meters (m). Do NOT use unit prefixes. For example, enter 1.75 for 175cm.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Weight type -->
    <xs:simpleType name="weight_type">
        <xs:annotation>
            <xs:documentation>
                Weight in grams (g). Do NOT use unit prefixes. For example, enter 75000 for 75kg.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Energy type -->
    <xs:simpleType name="energy_type">
        <xs:annotation>
            <xs:documentation>
                Energy in joules (J). Do NOT use unit prefixes. For example, enter 8368000 for 2000kcal.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Volume type -->
    <xs:simpleType name="volume_type">
        <xs:annotation>
            <xs:documentation>
                Volume in milliliters (mL). For example, enter 2000 for 2 liters of water.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Mass type -->
    <xs:simpleType name="mass_type">
        <xs:annotation>
            <xs:documentation>
                Mass in grams (g). Used for macronutrients and other nutritional values.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Micro mass type -->
    <xs:simpleType name="micro_mass_type">
        <xs:annotation>
            <xs:documentation>
                Mass in milligrams (mg). Used for micronutrients like calcium, sodium, etc.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Long term goals type -->
    <xs:complexType name="long_term_goals_type">
        <xs:sequence>
            <xs:element name="weight" type="weight_type"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- daily logs type -->
    <xs:complexType name="daily_logs_type">
        <xs:sequence>
            <xs:element name="daily_log" type="daily_log_type" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- daily log type -->
    <xs:complexType name="daily_log_type">
        <xs:sequence>
            <xs:element name="daily_goal" type="daily_goal_type"/>
            <xs:element name="meals" type="meals_type"/>
        </xs:sequence>
        <xs:attribute name="date" type="xs:date" use="required"/>
    </xs:complexType>
    
    <!-- daily goal type -->
    <xs:complexType name="daily_goal_type">
        <xs:sequence>
            <xs:element name="energy" type="energy_type"/>
            <xs:element name="water" type="volume_type"/>
            <xs:element name="protein" type="mass_type"/>
            <xs:element name="carbohydrates" type="carbohydrates_type"/>
            <xs:element name="fats" type="fats_type"/>
            <xs:element name="cholesterol" type="micro_mass_type"/>
            <xs:element name="fiber" type="mass_type"/>
            <xs:element name="calcium" type="micro_mass_type"/>
            <xs:element name="sodium" type="micro_mass_type"/>
            <xs:element name="salt" type="mass_type"/>
            <xs:element name="phe" type="micro_mass_type"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- carbohydrates_type -->
    <xs:complexType name="carbohydrates_type">
        <xs:sequence>
            <xs:element name="total" type="mass_type"/>
            <xs:element name="sugars" type="mass_type"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- fats type -->
    <xs:complexType name="fats_type">
        <xs:sequence>
            <xs:element name="total" type="mass_type"/>
            <xs:element name="saturated_fats" type="mass_type"/>
            <xs:element name="trans_fats" type="mass_type" minOccurs="0"/>
            <xs:element name="monosaturated_fats" type="mass_type" minOccurs="0"/>
            <xs:element name="polysaturated_fats" type="mass_type" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- meals type -->
    <xs:complexType name="meals_type">
        <xs:sequence>
            <xs:element name="meal" type="meal_type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- meal type -->
    <xs:complexType name="meal_type">
        <xs:sequence>
            <xs:element name="name" type="meal_name_type"/>
            <xs:element name="note" type="xs:string" minOccurs="0"/>
            <xs:element name="servings" type="servings_type"/>
            <xs:element name="ingredients" type="ingredients_type"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:nonNegativeInteger" use="required"/>
    </xs:complexType>
    
    <!-- meal name type -->
    <xs:simpleType name="meal_name_type">
        <xs:annotation>
            <xs:documentation>
                The name of the meal. Must contain at least one non-whitespace character.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value=".*\S.*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- serving type -->
    <xs:simpleType name="servings_type">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- ingredients type -->
    <xs:complexType name="ingredients_type">
        <xs:sequence>
            <xs:element name="ingredient" type="ingredient_type" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- ingredient type -->
    <xs:complexType name="ingredient_type">
        <xs:sequence>
            <xs:element name="name" type="ingredient_name_type"/>
            <xs:element name="brand" type="ingredient_brand_type" minOccurs="0"/>
            <xs:element name="serving" type="serving_type"/>
            <xs:element name="img" type="xs:anyURI"/>
            <xs:element name="base_values_per_100g" type="base_values_per_100g_type"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:nonNegativeInteger"/>
    </xs:complexType>
    
    <!-- ingredient name type -->
    <xs:simpleType name="ingredient_name_type">
        <xs:annotation>
            <xs:documentation>
                The name of the ingredient. It must contain at least one non-whitespace character.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value=".*\S.*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- ingredient brand type -->
    <xs:simpleType name="ingredient_brand_type">
        <xs:annotation>
            <xs:documentation>
                The brand of the ingredient. It must contain at least one non-whitespace character.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value=".*\S.*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- serving type -->
    <xs:complexType name="serving_type">
        <xs:annotation>
            <xs:documentation>
                Serving describes the amount of an ingredient and more useful details about the serving.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="count" type="serving_count_type"/>
            <xs:element name="weight" type="weight_type"/>
            <xs:element name="specification" type="serving_specification_type" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Serving count type -->
    <xs:simpleType name="serving_count_type">
        <xs:annotation>
            <xs:documentation>
                A unitless count representing the number of servings. Must be non-negative.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- serving specification type -->
    <xs:complexType name="serving_specification_type" mixed="true">
        <xs:annotation>
            <xs:documentation>
                Specification of the serving. It's an information to the user that makes it more clear how big is the serving.
            </xs:documentation>
        </xs:annotation>
        <xs:all>
            <xs:element name="size_category" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    
    <xs:complexType name="base_values_per_100g_type">
        <xs:sequence>
            <xs:element name="energy" type="energy_type"/>
            <xs:element name="protein" type="mass_type" minOccurs="0"/>
            <xs:element name="carbohydrates" type="carbohydrates_type" minOccurs="0"/>
            <xs:element name="fats" type="fats_type" minOccurs="0"/>
            <xs:element name="cholesterol" type="micro_mass_type" minOccurs="0"/>
            <xs:element name="fiber" type="mass_type" minOccurs="0"/>
            <xs:element name="calcium" type="micro_mass_type" minOccurs="0"/>
            <xs:element name="sodium" type="micro_mass_type" minOccurs="0"/>
            <xs:element name="salt" type="mass_type" minOccurs="0"/>
            <xs:element name="water" type="mass_type" minOccurs="0"/>
            <xs:element name="phe" type="micro_mass_type" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== MrLogEN/4iz238-sp/xml/diet_tracker.xml
<?xml version="1.0" encoding="UTF-8"?>
<diet_tracker version="1.0" xmlns="urn:vse:4iz238:chav07:sp:diet_tracker"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:vse:4iz238:chav07:sp:diet_tracker ../schemas/diet_tracker.xsd">
    <!-- All values use SI base units or their standard prefixes: -->
    <!-- Mass: grams (g) or milligrams (mg) -->
    <!-- Volume: milliliters (ml) - for water goals -->
    <!-- Energy: joules (J) -->
    <!-- Length: meters (m) -->
    <!-- Note: Water content in ingredients is in grams (g), which equals milliliters (ml) for water -->
    <user id="1">
        <name>Jan Novák</name>
        <email>jan.novak@example.cz</email>
        <date_of_birth>2025-12-03</date_of_birth>
        <sex>male</sex>
        <current_state>
            <height>1.77</height>
            <weight>81000</weight>
        </current_state>
        <long_term_goals>
            <weight>72000</weight>
        </long_term_goals>
        <daily_logs>
            <daily_log date="2025-11-21">
                <daily_goal>
                    <energy>8786400</energy>
                    <water>2200</water>
                    <protein>120</protein>
                    <carbohydrates>
                        <total>230</total>
                        <sugars>21</sugars>
                    </carbohydrates>
                    <fats>
                        <total>40</total>
                        <saturated_fats>5.93</saturated_fats>
                        <trans_fats>2.1</trans_fats>
                        <monosaturated_fats>3.7</monosaturated_fats>
                        <polysaturated_fats>1.32</polysaturated_fats>
                    </fats>
                    <cholesterol>450</cholesterol>
                    <fiber>2.25</fiber>
                    <calcium>12</calcium>
                    <sodium>35</sodium>
                    <salt>8</salt>
                    <phe>700</phe>
                </daily_goal>
                <meals>
                    <meal id="1">
                        <name>Jogurt s rohlíkem</name>
                        <note>Prostě jeden jogurt s rohlíkem</note>
                        <servings>1</servings>
                        <ingredients>
                            <ingredient id="1">
                                <name>Řecký jogurt bílý 0% tuku</name>
                                <brand>Milko</brand>
                                <serving>
                                    <count>1</count>
                                    <weight>130</weight>
                                </serving>
                                <img>https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%2Fid%2FOIP.fiEfxY1GbSjMAolRTkmJ4gHaGm%3Fpid%3DApi&amp;f=1&amp;ipt=74a317cda62ea5922647e4e78fe8c6204b38a407bc6f0dc4b3a20339e0145674</img>
                                <base_values_per_100g>
                                    <energy>259343.63</energy>
                                    <protein>10.77</protein>
                                    <carbohydrates>
                                        <total>3.77</total>
                                        <sugars>3.77</sugars>
                                    </carbohydrates>
                                    <fats>
                                        <total>0.32</total>
                                        <saturated_fats>0.22</saturated_fats>
                                    </fats>
                                    <salt>0.11</salt>
                                    <phe>540</phe>
                                </base_values_per_100g>
                            </ingredient>
                            <ingredient id="2">
                                <name>rohlík bílý</name>
                                <serving>
                                    <count>1</count>
                                    <weight>43</weight>
                                </serving>
                                <img>https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic.albert.cz%2Fmedias%2Fsys_master%2Fh48%2Fh20%2F9036897157150.jpg%3FbuildNumber%3D4540da3fc20f0f00761506c45e08edd452aee49058ae15a27beacf39029bc769&amp;f=1&amp;nofb=1&amp;ipt=dbe7997b3b8c6e709aff98c13bba7f72fea33bac4029a13ce08af1b4267ac267</img>
                                <base_values_per_100g>
                                    <energy>1266292.47</energy>
                                    <protein>9.56</protein>
                                    <carbohydrates>
                                        <total>56.14</total>
                                        <sugars>1.05</sugars>
                                    </carbohydrates>
                                    <fats>
                                        <total>3.60</total>
                                        <saturated_fats>1.16</saturated_fats>
                                        <monosaturated_fats>1.05</monosaturated_fats>
                                        <polysaturated_fats>1.05</polysaturated_fats>
                                    </fats>
                                    <fiber>4.35</fiber>
                                    <calcium>100</calcium>
                                    <water>0.03</water>
                                    <phe>480</phe>
                                </base_values_per_100g>
                            </ingredient>
                        </ingredients>
                    </meal>
                    <meal id="2">
                        <name>Míchaná vejce</name>
                        <note>Míchaná vajíčka smažená bez tuku na teflonu</note>
                        <servings>1</servings>
                        <ingredients>
                            <ingredient id="3">
                                <name>Vejce slepičí</name>
                                <serving>
                                    <count>5</count>
                                    <weight>60</weight>
                                    <specification>
                                        <size_category>M</size_category>
                                    </specification>
                                </serving>
                                <img>https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.istockphoto.com%2Fid%2F479882154%2Fcs%2Ffotografie%2Fjedno-vejce-izolovan%25C3%25A9-na-b%25C3%25ADl%25C3%25A9m-pozad%25C3%25AD.jpg%3Fs%3D612x612%26w%3D0%26k%3D20%26c%3DrbzSv87YtMz22ZSt74LTkNxCgCCMCNM4P3xsCf3Lrkg%3D&amp;f=1&amp;nofb=1&amp;ipt=93c2890d0d71f8296557020a69451c53f2b475d0e0eb1b55af72be555a4ddfe7</img>
                                <base_values_per_100g>
                                    <energy>1053833.33</energy>
                                    <protein>20.63</protein>
                                    <carbohydrates>
                                        <total>1.57</total>
                                        <sugars>0.57</sugars>
                                    </carbohydrates>
                                    <fats>
                                        <total>18.12</total>
                                        <saturated_fats>5.62</saturated_fats>
                                        <monosaturated_fats>7.17</monosaturated_fats>
                                        <polysaturated_fats>2.97</polysaturated_fats>
                                    </fats>
                                    <cholesterol>720</cholesterol>
                                    <phe>1030</phe>
                                </base_values_per_100g>
                            </ingredient>
                        </ingredients>
                    </meal>
                    <meal id="3">
                        <name>Číz v meku</name>
                        <servings>1</servings>
                        <ingredients>
                            <ingredient id="4">
                                <name>Cheeseburger</name>
                                <brand>McDonald's</brand>
                                <serving>
                                    <count>1</count>
                                    <weight>119</weight>
                                </serving>
                                <img>https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.mcdonalds.at%2Fwp-content%2Fuploads%2F2023%2F02%2F1500x1500-web-pop-neu-cheeseburger.png&amp;f=1&amp;nofb=1&amp;ipt=4090ecaa0f321a84234ca55a15667a602fac8eba9f6b769dda0d69afb547e004</img>
                                <base_values_per_100g>
                                    <energy>1056890.76</energy>
                                    <protein>12.96</protein>
                                    <carbohydrates>
                                        <total>24.92</total>
                                        <sugars>5.98</sugars>
                                    </carbohydrates>
                                    <fats>
                                        <total>10.97</total>
                                        <saturated_fats>4.98</saturated_fats>
                                        <trans_fats>1.76</trans_fats>
                                        <monosaturated_fats>3.11</monosaturated_fats>
                                        <polysaturated_fats>1.11</polysaturated_fats>
                                    </fats>
                                    <cholesterol>380</cholesterol>
                                    <fiber>1.89</fiber>
                                    <calcium>10</calcium>
                                    <sodium>30</sodium>
                                    <salt>2.52</salt>
                                    <phe>520</phe>
                                </base_values_per_100g>
                            </ingredient>
                        </ingredients>
                    </meal>
